Controllers/EEmainController.cs
using iText.IO.Font;
using iText.IO.Font.Constants;
using iText.Kernel.Colors;
using iText.Kernel.Font;
using iText.Kernel.Pdf;
using iText.Layout;
using iText.Layout.Element;
using PagedList;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Web.Mvc;
using System;
using System.Net;
using SEEIPro.Models;
using iText.IO.Image;
using iText.Kernel.Geom;

namespace SEEIPro.Controllers
{
    public class EEmainController : Controller
    {
        seeiExpertsDBEntities seeiDB = new seeiExpertsDBEntities();
        List<Expert> expts = new List<Expert>();
        //
        // GET: /MainPage/

        public ActionResult HomePage()
        {
            expts = seeiDB.Experts.ToList<Expert>();
            ViewData["total"] = expts.Count;
            return View();
        }

        public ActionResult ExpertProfile(int? page)
        {
            int PageNum = page ?? 1;
            int PageSize = int.Parse(ConfigurationManager.AppSettings["IndustrailPageSize"]);
            int total = 0;
            if (PageNum < 1)
            {
                PageNum = 1;
            }
            expts = seeiDB.Experts.ToList<Expert>();
            expts = GetExperts(expts, PageNum, PageSize, ref total);
            var pagedlist = new StaticPagedList<Expert>(expts, PageNum, PageSize, total);
            return View(pagedlist);
        }


        private List<Expert> GetExperts(List<Expert> list, int Pagenum, int pagesize, ref int total)
        {
            var exps = (from ept in list orderby ept.sId ascending select ept).Skip((Pagenum - 1) * pagesize).Take(pagesize);
            total = list.Count();
            return exps.ToList();
        }


        public ActionResult About()
        {
            return View();
        }
        public ActionResult Tools()
        {
            return View();
        }

        [HttpPost]
        public FileResult CreatePDF()
        {
            string[] urlLinks = new string[12];
            urlLinks = (string[])Request.Form["urls"].Split(',');
            string filepath = "E:\\demo.pdf";
            if (urlLinks[0].Length > 10)
            {
                System.Drawing.Image img = getOnineImage(urlLinks[0]);

               PdfWriter pdfwriter = new PdfWriter(filepath); 
                PdfDocument pdf = new PdfDocument(pdfwriter);
                iText.Layout.Document document = new iText.Layout.Document(pdf,PageSize.A4);
                PdfFont font = PdfFontFactory.CreateFont(StandardFonts.TIMES_ROMAN);
                document.Add(new Paragraph("This pdf is created by gongjing457!")).Add(new Image(ImageDataFactory.Create(img, System.Drawing.Color.White))).SetFont(font);
                document.Close();
                return File(new FileStream(filepath, FileMode.Open), "application/pdf", "demo");

            }
            else
            {
                return File(new FileStream(filepath, FileMode.Open), "application/pdf", "demo");
            }

        }

        private System.Drawing.Image getOnineImage(string url)
        {
            System.Drawing.Image image = null;
            try
            {
                WebRequest webrequest = WebRequest.Create(url);
                using (WebResponse response = webrequest.GetResponse())
                {
                    response.GetResponseStream();
                    if (response != null)
                    {
                        image = System.Drawing.Image.FromStream(response.GetResponseStream());
                    }
                }
            }
            catch (Exception)
            {
                image = null;
            }
            return image;
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @RenderBody()

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>

Views/Shared/_LayoutPageExpertsManagement.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/Content/css/ExpertsManage.css" rel="stylesheet" />
    <link type="image/x-icon" href="~/Content/images/favico.ico" rel="icon" />
</head>
<body>
    <div class="top">
        <span class="text-left">
            今天是 @Html.Label("yyyy-MM-DD", DateTime.Today.Date.ToLongDateString())，欢迎 @if (Session["name"] != null)
            {   @Session["name"]  }回来！
        </span>
        <span class="text-right">
            <a class="btn btn-link" href="@Url.Action("ChangePassword","Backstage")" title="点击修改密码">修改密码</a>
            <a class="btn btn-link" onclick="btnQuit(); return false;" title="点击返回首页">注销</a>
        </span>
    </div>
    <div class="container-fluid">
        <div class="div_left">
            <ul>
                <li><a href="@Url.Action("Index", "ExpertsManage")" title="查看专家列表"><span><img src="~/Content/images/iterm.jpg" /></span>专家信息列表</a> </li>
                <li> <a href="@Url.Action("Add", "ExpertsManage")" title="录入专家信息"><span><img src="~/Content/images/iterm.jpg" /></span>录入专家信息</a> </li>
                <li><a href="@Url.Action("Upload", "ExpertsManage")" title="专家相关附件上传(个人登记表、专家聘书等)"><span><img src="~/Content/images/iterm.jpg" /></span>专家附件上传</a></li>
            </ul>
        </div>
        <div class="div_right">
            @RenderBody()
        </div>
        <div class="clearfix"></div>

    </div>
    <div class="div_footer">
        <p>南方教育装备创新研究院&nbsp;&nbsp;版权所有 ©2018&nbsp;&nbsp;技术支持:<a href="https://weibo.com/gongjing457" target="_blank">Ryan</a> </p>
        <p> 联系电话：0750-3299695&nbsp;&nbsp;邮箱：jyzbyjy@126.com</p>
        <p> 地址：广东省江门市蓬江区群华路15号群华科技园5栋二层</p>
    </div>
</body>
</html>
<script>
    function btnQuit() {
        if (confirm("您确定要退出吗？")) {
            $.ajax({
                type: "POST",
                url: "/Backstage/Quit",
                cache: false,
                datatype: "json",
                success: function (res) {
                    res = JSON.parse(res);
                    alert(res.msg);
                    window.location = "/EEmain/HomePage";
                }, error: function () {
                    alert("当前处理过中出现了异常，请联系系统管理员！" + xhr.responseText);
                }
            });
        }
    }
</script>

Views/Shared/_LayoutPageTopMain.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>南方教育装备产业发展智库</title>
    <link type="image/x-icon" rel="icon" href="~/Content/images/favico.ico" />
    <link href="~/Scripts/bootstrap/css/bootstrap.min.css" rel="stylesheet" /> 
    <link href="~/Content/css/LayoutTopmain.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-2.1.4.min.js"></script>
    <script>
        $(function () {
            $(".nav").find("li").each(function () {
                var a = $(this).find("a:first")[0];
                if ($(a).attr("href") === location.pathname) {
                    $(this).addClass("active");
                } else {
                    $(this).removeClass("active");
                }
            });
        });
    </script>
</head>

<body>
    <div class="div-top">
        <span class="sp_title">南方教育装备产业发展智库</span>
        <span class="sp_content">南方教育装备创新研究院  主办</span>
    </div>

    <nav class="navbar navbar-default" role="navigation">
        <div>
            <ul class="nav navbar-nav">
                <li class="active"><a href="@Url.Action("HomePage", "EEmain")">首页</a></li>
                <li><a href="@Url.Action("About", "EEmain")">关于智库</a></li>
                <li><a href="@Url.Action("ExpertProfile", "EEmain")">智库专家</a></li>
                <li><a href="@Url.Action("Tools", "EEmain")">常用工具</a></li>
            </ul>
        </div>
        <div><p class="navbar-text navbar-right"><a class="btn-link" href="@Url.Action("Login", "Backstage")" target="_blank">管理登陆</a> </p></div>
    </nav>

    <div class="divider"></div>
    <div class="div_content">
        @RenderBody()
    </div>
    <div class="div_footer">
        <p>南方教育装备创新研究院&nbsp;&nbsp;版权所有 ©2018&nbsp;&nbsp;技术支持:<a href="https://weibo.com/gongjing457" target="_blank">Ryan</a> </p>
        <p> 联系电话：0750-3299695&nbsp;&nbsp;邮箱：jyzbyjy@126.com</p>
        <p> 地址：广东省江门市蓬江区群华路15号群华科技园5栋二层</p>
    </div>
</body>
</html>