Controllers/ExpertsManageController.cs
using SEEIPro.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.Entity.Infrastructure;
using System.Data.Entity.Validation;
using System.Linq;
using System.Web.Mvc;
using PagedList;
using System.Data;
using System.IO;
using SEEIPro.Utils;
using System.Globalization;

namespace SEEIPro.Controllers
{
    [LoginAuthorizationActionFilter(isCheck = true)]
    public class ExpertsManageController : Controller
    {
        private static seeiExpertsDBEntities seeiDb = new seeiExpertsDBEntities();
        List<UnitProperty> unitList = seeiDb.UnitProperties.ToList<UnitProperty>();
        List<StorageStatu> statusList = seeiDb.StorageStatus.ToList<StorageStatu>();

        [HttpGet]
        public ActionResult Index(int? page)
        {
            int PageNum = page ?? 1;
            string searchstring = Request.QueryString["search"];
            int PageSize = int.Parse(ConfigurationManager.AppSettings["PageSize"]);
            int total = 0;
            if (PageNum < 1)
            {
                PageNum = 1;
            }
            var experts = seeiDb.Experts.ToList();
            if (!String.IsNullOrEmpty(searchstring))
            {
                experts = experts.Where(e => e.eName.Contains(searchstring) || e.academicTitles.Contains(searchstring) || e.UnitDetailsOne.Contains(searchstring) || e.field.Contains(searchstring) || e.expertIntroduction.Contains(searchstring)).OrderBy(e => e.sId).ToList();
            }
            experts = GetExperts(experts, PageNum, PageSize, ref total);

            var pagedlist = new StaticPagedList<Expert>(experts, PageNum, PageSize, total);
            //通过ToPagedList扩展方法进行分页  
            //IPagedList<Expert> pagedlist = experts.ToPagedList();
            ViewBag.StatusList = statusList;
            return View(pagedlist);
        }
        private List<Expert> GetExperts(List<Expert> list, int Pagenum, int pagesize, ref int total)
        {
            var exps = (from ept in list orderby ept.sId ascending select ept).Skip((Pagenum - 1) * pagesize).Take(pagesize);
            total = list.Count();
            return exps.ToList();
        }

        /// <summary>
        /// GET: /ExpertsManage/Create添加新专家页面
        /// </summary>
        /// <returns></returns>
        public ActionResult Add()
        {
            ViewBag.UnitList = unitList;
            ViewBag.StatusList = statusList;
            return View();
        }

        public ActionResult Photo(int id)
        {
            if (id > 0)
            {
                Expert exp = (from expt in seeiDb.Experts where expt.sId == id select expt).FirstOrDefault();
                return View(exp);
            }
            else
            {
                Response.Write("<script>alert('请您确认要修改的专家编号!');window.location='/ExpertsManage/Index';</script>"); return null;
            }
        }

        /// <summary>
        /// save expert img icon
        /// </summary>
        /// <returns></returns> 
        public ActionResult SaveExpertImg(int id)
        {
            if (id > 0)
            {
                var expt = seeiDb.Experts.Find(id);
                expt.img = Request["imginfo"];
                seeiDb.Entry<Expert>(expt).State = EntityState.Modified;
                int res = seeiDb.SaveChanges();
                if (res > 0)
                {
                    return Json(new { status = "ok", msg = "该专家的图像已经修改并成功保存！" }, "text/html", JsonRequestBehavior.AllowGet);
                }
                else { return Json(new { status = "no", msg = "该专家图像已经修改过了！" }, "text/html", JsonRequestBehavior.AllowGet); }
            }
            else { return Json(new { status = "error", msg = "请确认要修改的专家编号！" }, "text/html", JsonRequestBehavior.AllowGet); }
        }

        /// <summary>
        /// GET: /ExpertsManage/Upload
        /// </summary>
        /// <param name="page"></param>
        /// <returns></returns>
        public ActionResult Upload(int? page)
        {
            int PageNum = page ?? 1;
            int PageSize = int.Parse(ConfigurationManager.AppSettings["PageSize"]);
            int total = 0;
            if (PageNum < 1)
            {
                PageNum = 1;
            }
            var experts = GetExperts(seeiDb.Experts.ToList(), PageNum, PageSize, ref total);
            var pagedlist = new StaticPagedList<Expert>(experts, PageNum, PageSize, total);
            //通过ToPagedList扩展方法进行分页  
            //IPagedList<Expert> pagedlist = experts.ToPagedList();
            ViewBag.StatusList = statusList;
            return View(pagedlist);
        }

        /// <summary>
        /// GET/filedownload/
        /// </summary>
        /// <param name="id">eid</param>
        /// <returns> FileResult</returns>
        public FileStreamResult FileDownload(int id)
        {
            string fileurl = "";
            var file_type = Request["type"];
            if (id > 0)
            {
                var expert = seeiDb.Experts.Find(id);
                switch (file_type)
                {
                    case "register":
                        fileurl = expert.registrationForm;
                        break;
                    case "certificate":
                        fileurl = expert.appointmentBook;
                        break;
                }
                string filepath = Server.MapPath(fileurl);
                string fileExt = Path.GetExtension(fileurl);
                string filedownloadname = DateTime.Now.ToString("yyyyMMddHHmmssffff", DateTimeFormatInfo.InvariantInfo) + fileExt;
                if (!System.IO.File.Exists(filepath))
                {
                    Response.Write("<script>alert('您当前下载文件不存在，请核对后重试！');window.close();</script>"); return null;
                }
                else
                {
                    return File(new FileStream(filepath, FileMode.Open), "application/pdf", filedownloadname);
                }

            }
            else
            {
                Response.Write("<script>alert('请您确认要下载文件所对应的专家编号!');window.close();</script>");
                return null;
            }

        }

        /// <summary>
        /// POST: /ExpertsManage/保存专家信息
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public ActionResult SaveExpert()
        {
            string eid = Request["eId"];
            string eName = Request["eName"];
            string gender = Request["gender"];
            string birthDay = Request["birthDay"];
            string imginfo = Request["imgUrl"];
            string identityNumber = Request["identityNumber"];
            string unitProperty = Request["unitProperty"];
            string unitOne = Request["unitOne"];
            string unitTwo = Request["unitTwo"];
            string unitThree = Request["unitThree"];
            string academicTitles = Request["academicTitles"];
            string field = Request["field"];
            string email = Request["email"];
            string officePhone = Request["officePhone"];
            string cellPhone = Request["cellPhone"];
            string postalAddress = Request["postalAddress"];
            string expertSources = Request["expertSources"];
            string beStatus = Request["beStatus"];
            string personalUrl = Request["personalUrl"];
            string Categories = Request["Categories"];
            string expertIntroduction = Request["expertIntroduction"];
            string expertworkingExperience = Request["expertworkingExperience"];
            string expertAchievement = Request["expertAchievement"];
            string remark = Request["remark"];
            if (eid != null && eid.Length > 0)
            {
                Expert expert = new Expert();
                expert.eId = eid;
                expert.eName = eName;
                expert.gender = gender;
                expert.birthDay = Convert.ToDateTime(birthDay);
                expert.identityNumber = identityNumber;
                expert.unitProperty = Convert.ToInt32(unitProperty);
                expert.UnitDetailsOne = unitOne;
                expert.UnitDetailsTwo = unitTwo;
                expert.UnitDetailsThree = unitThree;
                expert.academicTitles = academicTitles;
                expert.field = field;
                expert.email = email;
                expert.officePhone = officePhone;
                expert.cellPhone = cellPhone;
                expert.postalAddress = postalAddress;
                expert.expertSources = expertSources;
                expert.beStatus = Convert.ToInt32(beStatus);
                if (imginfo != null)
                {
                    expert.img = imginfo;
                }
                else
                {
                    expert.img = "/Content/xiaoyicun/obama.jpg";
                }
                expert.personalUrl = personalUrl;
                expert.Categories = Categories;
                expert.SerialNum = eid.Substring(eid.Length - 4);
                expert.expertIntroduction = expertIntroduction;
                expert.expertworkingExperience = expertworkingExperience;
                expert.expertAchievement = expertAchievement;
                expert.remark = remark;
                expert.addTime = DateTime.Now.ToLocalTime();
                seeiDb.Experts.Add(expert);
                if (seeiDb.SaveChanges() > 0)
                {
                    return Json(new { status = "ok", msg = "该专家信息已经保存成功！" }, "text/html", JsonRequestBehavior.AllowGet);      //wrong pwd
                }
                else
                {
                    return Json(new { status = "no", msg = "该专家信息可能已经存在！" }, "text/html", JsonRequestBehavior.AllowGet);      //wrong pwd
                }
            }
            else
            {
                return Json(new { status = "error", msg = "请确认要保存的专家信息后，再提交保存！" }, "text/html", JsonRequestBehavior.AllowGet);      //wrong pwd
            }
        }

Views/ExpertsManage/Details.cshtml
@model SEEIPro.Models.Expert

@{
    ViewBag.Title = "专家详情页";
    Layout = "~/Views/Shared/_LayoutPageExpertsManagement.cshtml";
}

@using SEEIPro.Models

<link href="~/Scripts/bootstrap/css/bootstrap.min.css" rel="stylesheet" />

@if (Model != null)
{
    <div class="container-fluid">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="text-center">专家详情页</h3>
            </div>
            <div class="panel-body">
                <div class="panel">姓名：@Model.eName</div>
                <img class="expert-photo" style="width:130px;height:130px;position:absolute;right:15%;top:30%;" src="@Model.img" />
                <div class="panel">性别：@Model.gender</div>
                <div class="panel">
                    单位性质：
                    @foreach (UnitProperty unit in ViewBag.UnitList as List<UnitProperty>)
                    {
                        if (unit.id == Model.unitProperty)
                        {
                    @unit.unitProperties
                        }
                    }
                </div>
                <div class="panel">工作单位及职务：@Model.UnitDetailsOne</div>
                <div class="panel">邮箱：</div>
                <div class="panel">移动电话：@Model.cellPhone</div>
                <div class="panel">通讯地址：@Model.postalAddress</div>
                <div class="panel">业务分类：@Model.Categories</div>
            </div>
            <div class="panel panel-info">
                <div class="panel-heading">个人简介（管理业务、研究方向）</div>
                <div class="panel-body">
                    @Model.expertIntroduction
                </div>
            </div>
            <div class="panel panel-success">
                <div class="panel-heading">主要工作简历（参加工作的经历）</div>
                <div class="panel-body">
                    @Model.expertworkingExperience
                </div>
            </div>
            <div class="panel panel-danger">
                <div class="panel-heading">主要工作业绩（所承担的项目、成果、专利、著作、已发表论文、研究报告、获奖情况等方面的介绍）</div>
                <div class="panel-body">
                    @Model.expertAchievement
                </div>
            </div>
            <div class="text-center">
                <a class="btn btn-primary" href="@Url.Action("Edit", "ExpertsManage", new { id = Model.sId })" title="点击进行修改">点击修改</a>
                <a class="btn btn-danger" href="@Url.Action("Index", "ExpertsManage")" title="点击返回专家列表">返回列表</a>
            </div> 
        </div>
      
    </div>

}
else
{
    <p class="text-danger">没有内容！</p>
}

Views/ExpertsManage/Edit.cshtml
@model SEEIPro.Models.Expert

@{
    ViewBag.Title = "编辑专家信息";
    Layout = "~/Views/Shared/_LayoutPageExpertsManagement.cshtml";
}

@using SEEIPro.Models;

<link href="~/Scripts/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
<link href="~/Content/css/base.css" rel="stylesheet" />
<div class="container-fluid">
    <h3 class="text-center">编辑专家信息</h3>
    @using (Html.BeginForm("Edit", "ExpertsManage", FormMethod.Post))
    {
        //Expert expert = (Expert)ViewData["exptinfo"];
        if (Model != null)
        {
            <input type="hidden" name="sid" value="@Model.sId" />
            <div class="panel panel-default">
                <div class="panel-heading">基本信息</div>
                <div class="panel-body">
                    <div class="form-group">
                        <label class="control-label">专家编号<span class="text-danger">*</span></label>
                        <div class="controls">
                            <input class="form-control" type="text" name="eId" title="修改专家编号" value="@Model.eId" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label">姓名<span class="text-danger">*</span></label>
                        <div class="controls">
                            <input class="form-control" type="text" name="eName" title="修改姓名" value="@Model.eName" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label">性别<span class="text-danger">*</span></label>
                        <div class="controls">
                            <select class="form-control" name="gender" title="选择性别">
                                @if (Model.gender.Equals("男"))
                                {
                                <option selected="selected" value="男">男</option>
                                }
                                else
                                {
                                <option value="男">男</option>
                                }
                                @if (Model.gender.Equals("女"))
                                {
                                <option selected="selected" value="女">女</option>
                                }
                                else
                                {
                                <option value="女">女</option>
                                }
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label">出生日期</label>
                        <div class="controls">
                            <input class="form-control" type="text" name="birthDay" title="请选择出生日期" value="@Convert.ToDateTime(Model.birthDay).ToShortDateString()" onclick="WdatePicker({ mindate: '1900-01-01', maxdate: '%y-%M-%d' })" readonly />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label">身份证号</label>
                        <div class="controls">
                            <input type="text" class="form-control" name="identityNumber" title="修改18位身份证号" value="@Model.identityNumber" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label">技术职称</label>
                        <div class="controls">
                            <input type="text" class="form-control" name="academicTitles" title="修改技术职称" value="@Model.academicTitles" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label">单位性质</label>
                        <div class="controls">
                            <select name="unitProperty" class="form-control" title="请选择单位性质(注：所填第一个单位性质)！">
                                @foreach (UnitProperty unit in @ViewBag.UnitList as List<UnitProperty>)
                                {
                                    if (unit.id == Model.unitProperty)
                                    {
                                <option selected="selected" value="@unit.id">@unit.unitProperties</option>
                                    }
                                    else
                                    {
                                <option value="@unit.id">@unit.unitProperties</option>
                                    }
                                }
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label">单位信息</label>
                        <div class="controls">
                            <input type="text" class="form-control" name="UnitDetailsOne" title="主要单位信息" value="@Model.UnitDetailsOne" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label">单位二(名称; 部门;职务)</label>
                        <div class="controls">
                            <input type="text" class="form-control" name="UnitDetailsTwo" title="可选填单位信息" value="@Model.UnitDetailsTwo" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label">单位三(名称;部门;职务)</label>
                        <div class="controls">
                            <input type="text" class="form-control" name="UnitDetailsThree" title="可选填单位信息" value="@Model.UnitDetailsThree" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label">业务分类<span class="text-danger">*</span></label>
                        <div class="controls">
                            <input type="text" class="form-control" name="Categories" title="修改业务分类" value="@Model.Categories" />
                        </div>
                    </div>
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-heading">联系方式</div>
                <div class="panel-body">
                    <div class="form-group">
                        <label class="control-label">办公电话<span class="text-danger">*</span></label>
                        <div class="controls">
                            <input type="text" class="form-control" name="officePhone" title="修改办公电话" value="@Model.officePhone" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label">移动电话<span class="text-danger">*</span></label>
                        <div class="controls">
                            <input type="text" class="form-control" name="cellPhone" title="修改移动电话" value="@Model.cellPhone" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label">邮箱<span class="text-danger">*</span></label>
                        <div class="controls">
                            <input type="text" class="form-control" name="email" title="修改邮箱" value="@Model.email" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label">通讯地址<span class="text-danger">*</span></label>
                        <div class="controls">
                            <input type="text" class="form-control" name="postalAddress" title="修改通信地址" value="@Model.postalAddress" />
                        </div>
                    </div>
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-heading">专家学术情况</div>
                <div class="panel-body">
                    <div class="form-group">
                        <label class="control-label">从事领域<span class="text-danger">*</span></label>
                        <div class="controls">
                            <input type="text" class="form-control" name="field" title="修改专家从事领域" value="@Model.field" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label">相关主页</label>
                        <div class="controls">
                            <input type="text" class="form-control" name="personalUrl" title="修改专家相关主页" value="@Model.personalUrl" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label">个人简介(请写清主要管理业务、研究方向，300字以内)</label>
                        <div class="controls">
                            <textarea class="form-control multitext" name="expertIntroduction" title="专家个人的业务以及研究方向简介">@Model.expertIntroduction</textarea>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label">主要工作经历(300字以内)</label>
                        <div class="controls">
                            <textarea class="form-control multitext" name="expertworkingExperience" title="主要工作经历">@Model.expertworkingExperience</textarea>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label">主要工作业绩(包括承担项目、成果、专利、著作、论文、研究报告、获奖情况等，100字以内)</label>
                        <div class="controls">
                            <textarea class="form-control multitext" name="expertAchievement" title="主要工作业绩">@Model.expertAchievement</textarea>
                        </div>
                    </div>
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-heading">其他信息</div>
                <div class="panel-body">
                    <div class="form-group">
                        <label class="control-label">专家来源</label>
                        <div class="controls">
                            <input type="text" class="form-control" name="expertSources" title="修改专家来源" value="@Model.expertSources" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label">入库状态<span class="text-danger">*</span></label>
                        <div class="controls">
                            <select class="form-control" name="beStatus" title="请选择入库状态!">
                                @foreach (StorageStatu status in @ViewBag.statusList as List<StorageStatu>)
                                {
                                    if (status.sid == Model.beStatus)
                                    {
                                        <option selected="selected" value="@status.sid">@status.beStatus</option>
                                    }
                                    else
                                    {
                                        <option value="@status.sid">@status.beStatus</option>
                                    }
                                }
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label">备注</label>
                        <div class="controls">
                            <input class="form-control" type="text" name="remark" title="修改备注说明" value="@Model.remark" />
                        </div>
                    </div>
                </div>
            </div>
            <div class="control-group">
                <div class="pager">
                    <div class="controls">
                        <input class="btn btn-primary" type="submit" title="点击确认，保存修改信息" value="确认修改" />
                        <input class="btn btn-danger" type="button" title="取消信息编辑，返回专家列表" value="取消返回" id="btnCancel" />
                    </div>
                </div>
            </div>
        }
        else
        { <p class="text-danger">没有内容！</p> }
    }
</div>
<script src="~/Scripts/jquery-2.1.4.min.js"></script>
<script src="~/Scripts/My97DatePicker/WdatePicker.js"></script>
<script type="text/javascript">
    $(function () {
        $("#btnCancel").click(function () {
            if (confirm("您确定取消修改该专家信息吗？")) {
                window.location = "/ExpertsManage/Index";//cancel
            } else { return false; }
        });

    });
</script>

Views/ExpertsManage/Index.cshtml
@model PagedList.StaticPagedList<Expert>
@{
    ViewBag.Title = "专家信息列表";
    Layout = "~/Views/Shared/_LayoutPageExpertsManagement.cshtml";
}

@using SEEIPro.Models;
@using PagedList.Mvc;

<link href="~/Content/css/PagedList.css" rel="stylesheet" />
<link href="~/Scripts/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
<link href="~/Content/css/base.css" rel="stylesheet" />
 
@if (Model != null)
{
    <div class="div-head">
        关键词：<input type="text" class="input-sm textbox" id="txt_kwds" placeholder="如:教授" title="请输入要查询到的任意关键词！(姓名，职称，单位名称)" />
        <input type="button" class="btn btn-primary" id="btn_query" value="查询" title="点击查询" />
        <a class="text-right" href="@Url.Action("OutToExcel", "ExpertsManage")" title="点击到处到excel文件">导出到Excel文件</a>
    </div>
    <h3 class="text-center">入库专家信息列表</h3>
    <table class="table table-hover table-bordered">
        <thead>
            <tr>
                <th>专家序号</th>
                <th>姓名</th>
                <th>性别</th>
                <th>单位名称</th>
                <th>技术职称</th>
                <th>入库状态</th>
                <th>专家图像信息</th>
                <th>个人主页</th>
                <th>操作</th>
            </tr>
        </thead>
        <tbody>
            @foreach (Expert expert in Model)
            {
                <tr>
                    <td>@expert.sId</td>
                    <td>@expert.eName</td>
                    <td>@expert.gender</td>
                    <td>@expert.UnitDetailsOne</td>
                    <td>@expert.academicTitles</td>
                    <td>
                        @foreach (StorageStatu status in @ViewBag.StatusList as List<StorageStatu>)
                    {
                        if (expert.beStatus == status.sid)
                        {   @status.beStatus }
                    }
                    </td>
                    <td>
                        <a class="alink" href="@Url.Action("Photo", "ExpertsManage", new { id = expert.sId })" title="修改图像文件">修改专家图像</a>
                    </td>
                    <td>
                        @if (expert.personalUrl == null || expert.personalUrl.Length <= 16)
                        { <a class="alink" href="@Url.Action("Details", "ExpertsManage", new { id=expert.sId})" title="点击前往专家个人主页查看详情">查看详情页</a>  }
                    else
                    {
                            <a class="alink" href="@expert.personalUrl " target="_blank" title="点击前往专家个人主页查看详情">查看相关主页</a> }
                    </td>
                    <td>
                        <a href="@Url.Action("Edit", "ExpertsManage", new { id = expert.sId })" title="点击编辑专家信息">编辑</a>
                        <a class="alink" onclick="btnDel(@expert.sId)" title="点击删除专家">删除</a>
                    </td>
                </tr>
            }
        </tbody>
    </table> 
        <div class="col-sm-6 col-md-6">
            @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page }), new PagedListRenderOptions { LinkToFirstPageFormat = "首页", LinkToPreviousPageFormat = "上一页", LinkToNextPageFormat = "下一页", LinkToLastPageFormat = "尾页", DisplayLinkToFirstPage = PagedListDisplayMode.Always, DisplayLinkToLastPage = PagedListDisplayMode.Always, DisplayLinkToNextPage = PagedListDisplayMode.Always, DisplayLinkToPreviousPage = PagedListDisplayMode.Always, MaximumPageNumbersToDisplay =3 })
        </div>
        <div class="col-sm-6 col-md-6">
            每页 @Model.PageSize 条记录，共 @Model.PageCount 页，当前第 @Model.PageNumber 页,共 @Model.Count 条记录
            @Html.PagedListGoToPageForm((PagedList.IPagedList)Model, "Index", new GoToFormRenderOptions { LabelFormat = "跳转到：" })
        </div>
   
}
else
{
    <h3 class="text-center">入库专家信息列表</h3>
    <p class="text-danger">没有内容！</p>
}
<script src="~/Scripts/jquery-2.1.4.min.js"></script>
<script src="~/Scripts/bootstrap/js/bootstrap.min.js"></script>
<script>
    $(function () {
        //模糊查询
        $("#btn_query").click(function () {
            var kwd = $.trim($("#txt_kwds").val());
            if (kwd == "" || kwd.length == 0) {
                alert("请输入要查询的关键词！");
            } else {
                window.location = "/ExpertsManage/Index?search=" + kwd;
            }
        }); 
    });
            
    //删除专家
    function btnDel(sid) {
        if (confirm("您确定要删除该专家吗？")) {
            $.ajax({
                type: "GET",
                url: "/ExpertsManage/Delete?id=" + sid,
                datatype: "json",
                success: function (result) {
                    result = JSON.parse(result);
                    if (result.status == 'ok') {
                        alert(result.msg);
                        window.location = "/ExpertsManage/Index";
                    } else {
                        alert(result.msg);
                        return false;
                    }
                },
                error: function (xhr) {
                    alert("删除出现异常，请稍后重试！" + xhr.responsetext);
                }
            });
        } else { return false; }
    }


</script>